/**
 * TO BE DONE BY AIDAN EILER
 * 
 * THIS MODULE TRIES TO CALCULATES THE PROBABILITY OF A PLAYER WINNING A GAME OF
 * POKER BASED ON THEIR CURRENT HAND AND THE STATE OF THE GAME.
 * 
 * THE MODULE SHOULD QUERY A[T LEAST ONE] DATABASE IN ORDER TO FETCH PARAMETERS.
 * IT WILL TRY TO RETREIVE:
 * - THE HAND (2 CARDS)
 * - CARDS ON THE TABLE (3-5 CARDS)
 * - THE CARDS CURRENTLY IN THE DECK (ALSO INCLUDES THE PLAYERS' HANDS)
 * 
 * THE MODULE SHOULD RETURN A NUMERICAL VALUE SHOWING THE PROABILITY OF A PLAYER
 * WINNING GIVEN THEIR PARTICULAR HAND.
 */
