name: final_project_flutter_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flame: ^1.27.0
  flame_tiled: ^3.0.0
  flame_audio: ^2.11.3
  firebase_auth: ^5.5.2
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.7
  poker:
    path: ./packages/poker

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/art/
    - assets/images/art/cards/
    - assets/images/art/buttons/
    - assets/fonts/
    - assets/audio/
    - assets/audio/music/
