on:
  workflow_dispatch:
    
name: "Flutter CI"

jobs:
  build:

    defaults:
      run:
        working-directory: ./final_project_flutter_app
        
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "zulu"
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          architecture: "x64"

      - run: flutter build apk --release
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "final_project_flutter_app/build/app/outputs/apk/release/*"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
